"""add comment to evaluations

Revision ID: 377d5b44fc9b
Revises: 5256588b5769
Create Date: 2026-05-31 17:22:40.873019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377d5b44fc9b'
down_revision: Union[str, Sequence[str], None] = '5256588b5769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'comment')
    # ### end Alembic commands ###
